In [1]:
import numpy as np

**Creating an array with start, stop, step**

In [4]:
a = np.arange(0,10,2)
a
#use reshape to turn into 2D, 3D, etc... 

array([0, 2, 4, 6, 8])

**Creating a 1D array of 1s**

In [6]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

**Creating a 2D array of 1s**

In [27]:
bb = np.ones((3,3))
bb

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Creating a 1D array of zeros**

In [7]:
c = np.zeros(6)
c 

array([0., 0., 0., 0., 0., 0.])

**Creating a 2D array of zeros**

In [26]:
cc = np.zeros((3,3))
cc

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

**Arrays using linspace** 

In [8]:
d = np.linspace(5,10,3)
d
# use linspace to create arrays where the elements are equally spaced apart. 

array([ 5. ,  7.5, 10. ])

**Generate an array of random values**

In [29]:
e = np.random.randint(2,10,4)
e
# array random values

array([7, 2, 9, 3])

**Generate a 2D array of randome values**

In [32]:
ee = np.random.randint(2, 50, (2, 2))
ee

array([[40, 16],
       [31, 20]])

**Create an array with uniform distribution, (all numbers are equally likely to appear)**

In [34]:
f = np.random.rand(10)
f
# Anything between 0-1 has an equali likelihood of appearing. 

array([0.77074801, 0.32450102, 0.69414997, 0.91706733, 0.89537615,
       0.84238271, 0.10646471, 0.82728296, 0.21176632, 0.91530737])

**Array of values with normal distribution, where numbers closer to the mean are likely to be chosen**

In [35]:
g = np.random.randn(10)
g
# Numbers closer to the mean of 0, are more likely to appear

array([ 0.07201624, -2.28933482, -0.29532793,  0.92407164,  1.49446431,
       -0.90348527,  1.01935281, -1.16446302,  0.37120535, -0.24134443])

**Identity matrix**

In [13]:
h = np.eye(3)
h
# identity matrix. 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])